### PR TITLE
Add examples

### LINKED ISSUE #23: Identifying and adding old notebooks to new repo and adjusting to current environment
I'm starting now to go through the old notebooks and find what is most relevant still. I have now identified:
- [x] Masked and weighted avg: https://pangeo-data.github.io/escience-2022/examples/notebooks/masked_and_weighted_average.html
- [x] Is this one still the way to access ebas? https://pangeo-data.github.io/escience-2022/examples/notebooks/from_ebas_using_xarray.html
- [x] Using cartopy and projections: https://pangeo-data.github.io/escience-2022/examples/notebooks/projections.html
- [x] Is this still the way to access aeronet data? https://pangeo-data.github.io/escience-2022/examples/notebooks/read-AERONET.html
- [x] Regridding: https://pangeo-data.github.io/escience-2022/examples/notebooks/xesmf_regridding.html
- [x] I am also making one on hybrid sigma to pressure coordinates. 

@MichaelSchulzMETNO maybe you have some opinions on this?

### PR DESCRIPTION
**Pull request by sarambl**
Added the rest of the examples.

### CODE REVIEW

**Comment by mvdebolskiy** [comment]
You've got rid of the header and img errors? Should I merge that?

**Comment by mvdebolskiy** [comment]
Very cool. 
```
\docs\data\Intake-data-acess.ipynb:40002: WARNING: duplicate label reading and browsing the catalog, other 
instance in \docs\learning/notebooks/projections.ipynb
\docs\learning/notebooks/interpolate_hybridsigma2pressure_coords.ipynb:50002: WARNING: Document headings start at H3, not H1 [myst.header]

\docs\learning/notebooks/interpolate_hybridsigma2pressure_coords.ipynb:70003: WARNING: Document headings start at H3, not H1 [myst.header]

\docs\learning/notebooks/interpolate_hybridsigma2pressure_coords.ipynb:100002: WARNING: Document headings start at H3, not H1 [myst.header]

\docs\learning/notebooks/interpolate_hybridsigma2pressure_coords.ipynb:140002: WARNING: Document headings start at H3, not H1 [myst.header]

\docs\learning\notebooks\interpolate_hybridsigma2pressure_coords.ipynb:50002: WARNING: duplicate label open cmip6 online catalog,
 other instance in \docs\learning/notebooks/some-xarray-pandas-presentation_Sara.ipynb
\docs\learning\notebooks\interpolate_hybridsigma2pressure_coords.ipynb:70003: WARNING: duplicate label search corresponding data,
 other instance in \docs\learning/notebooks/some-xarray-pandas-presentation_Sara.ipynb
\docs\learning\notebooks\interpolate_hybridsigma2pressure_coords.ipynb:100002: WARNING: duplicate label create dictionary from the list of datasets we found,
 other instance in \docs\learning/notebooks/some-xarray-pandas-presentation_Sara.ipynb
\docs\learning/notebooks/some-xarray-pandas-presentation_Sara.ipynb:70003: WARNING: Non-consecutive header 
level increase; H1 to H4 [myst.header]
\docs\learning/notebooks/some-xarray-pandas-presentation_Sara.ipynb:100003: WARNING: Non-consecutive header level increase; H1 to H3 [myst.header]
\docs\learning/notebooks/some-xarray-pandas-presentation_Sara.ipynb:140002: WARNING: Non-consecutive header level increase; H1 to H3 [myst.header]
\docs\learning/notebooks/some-xarray-pandas-presentation_Sara.ipynb:170002: WARNING: Non-consecutive header level increase; H1 to H3 [myst.header]
\docs\learning/notebooks/some-xarray-pandas-presentation_Sara.ipynb:260002: WARNING: Non-consecutive header level increase; H2 to H5 [myst.header]
\docs\learning/notebooks/some-xarray-pandas-presentation_Sara.ipynb:290002: WARNING: Non-consecutive header level increase; H1 to H4 [myst.header]
\docs\learning/notebooks/some-xarray-pandas-presentation_Sara.ipynb:320002: WARNING: Non-consecutive header level increase; H1 to H3 [myst.header]
\docs\learning/notebooks/some-xarray-pandas-presentation_Sara.ipynb:340002: WARNING: Non-consecutive header level increase; H3 to H5 [myst.header]
\docs\learning/notebooks/some-xarray-pandas-presentation_Sara.ipynb:360002: WARNING: Non-consecutive header level increase; H1 to H3 [myst.header]
\docs\learning/notebooks/some-xarray-pandas-presentation_Sara.ipynb:720002: WARNING: Non-consecutive header level increase; H1 to H3 [myst.header]
docs\learning\notebooks\some-xarray-pandas-presentation_Sara.ipynb:60003: WARNING: image file not readable:
 learning/notebooks/attachment:4f3ffb45-6681-426e-a674-87ff7d3a7472.png
\docs\learning\notebooks\some-xarray-pandas-presentation_Sara.ipynb:60007: WARNING: image file not readable: 
learning/notebooks/attachment:1f171b31-582b-4003-be00-7d731d031ab9.png
\docs\learning\notebooks\some-xarray-pandas-presentation_Sara.ipynb:100003: WARNING: duplicate label search corresponding data,
 other instance in \docs\learning/notebooks/interpolate_hybridsigma2pressure_coords.ipynb
\docs\learning\notebooks\some-xarray-pandas-presentation_Sara.ipynb:140002: WARNING: duplicate label create dictionary from the list of datasets we found,
 other instance in \docs\learning/notebooks/interpolate_hybridsigma2pressure_coords.ipynb
\docs\learning\notebooks\xesmf_regridding.ipynb:20002: WARNING: duplicate label import python packages,
 other instance in \docs\learning/notebooks/some-xarray-pandas-presentation_Sara.ipynb
\docs\learning\notebooks\xesmf_regridding.ipynb:90002: WARNING: duplicate label open cmip6 online catalog, 

other instance in \docs\learning/notebooks/interpolate_hybridsigma2pressure_coords.ipynb
\docs\learning\notebooks\xesmf_regridding.ipynb:140002: WARNING: duplicate label create dictionary from the list of datasets we found,
 other instance in \docs\learning/notebooks/some-xarray-pandas-presentation_Sara.ipynb
```

**Comment by mvdebolskiy** [comment]
@sarambl Ok. fixed warnings by just suppressing them. Also [this issue](https://github.com/sphinx-gallery/sphinx-gallery/issues/120) was relevant.

**Comment by sarambl** [comment]
haha, sorry @mvdebolskiy

**Comment by mvdebolskiy** [comment]
Merging master into your working branch is totally fine.

**Comment by sarambl** [comment]
I said sorry for all the warnings. Can I merge the pull request now? It's all checked now.

**Pull request merged**
